# Generated by Django 5.1.6 on 2025-04-02 04:31

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_licence_number', models.CharField(max_length=50)),
                ('driver_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('student_pickup_latitude', models.FloatField()),
                ('student_pickup_longitude', models.FloatField()),
                ('student_dropoff_latitude', models.FloatField()),
                ('student_dropoff_longitude', models.FloatField()),
                ('parent_name', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('bus_speed', models.IntegerField()),
                ('drivers', models.ManyToManyField(related_name='buses', to='notification_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.IntegerField(primary_key=True, serialize=False)),
                ('notification_time', models.TimeField(auto_now=True)),
                ('bus_location_latitude', models.FloatField()),
                ('bus_location_longitude', models.FloatField()),
                ('notification_message', models.TextField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification_app.bus')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Smartcard',
            fields=[
                ('smartcard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('status', models.TextField()),
                ('validity', models.DateField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusAttendanceLog',
            fields=[
                ('scan_log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('boarding_timestamp', models.DateTimeField(auto_now_add=True)),
                ('alighting_timestamp', models.DateTimeField(blank=True, null=True)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification_app.bus')),
                ('smartcard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification_app.smartcard')),
            ],
        ),
    ]
